/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewImageIdRouteImport } from './routes/view.$imageId'
import { Route as ApiImageImageIdRouteImport } from './routes/api/image/$imageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewImageIdRoute = ViewImageIdRouteImport.update({
  id: '/view/$imageId',
  path: '/view/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageImageIdRoute = ApiImageImageIdRouteImport.update({
  id: '/api/image/$imageId',
  path: '/api/image/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/view/$imageId': typeof ViewImageIdRoute
  '/api/image/$imageId': typeof ApiImageImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/view/$imageId': typeof ViewImageIdRoute
  '/api/image/$imageId': typeof ApiImageImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/view/$imageId': typeof ViewImageIdRoute
  '/api/image/$imageId': typeof ApiImageImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/view/$imageId' | '/api/image/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/view/$imageId' | '/api/image/$imageId'
  id: '__root__' | '/' | '/view/$imageId' | '/api/image/$imageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ViewImageIdRoute: typeof ViewImageIdRoute
  ApiImageImageIdRoute: typeof ApiImageImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$imageId': {
      id: '/view/$imageId'
      path: '/view/$imageId'
      fullPath: '/view/$imageId'
      preLoaderRoute: typeof ViewImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/$imageId': {
      id: '/api/image/$imageId'
      path: '/api/image/$imageId'
      fullPath: '/api/image/$imageId'
      preLoaderRoute: typeof ApiImageImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ViewImageIdRoute: ViewImageIdRoute,
  ApiImageImageIdRoute: ApiImageImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
