/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ViewImageIdRouteImport } from './routes/view.$imageId'
import { Route as GalleryGalleryIdRouteImport } from './routes/gallery.$galleryId'
import { Route as ApiImageImageIdRouteImport } from './routes/api/image/$imageId'
import { Route as ApiGalleryGalleryIdRouteImport } from './routes/api/gallery/$galleryId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewImageIdRoute = ViewImageIdRouteImport.update({
  id: '/view/$imageId',
  path: '/view/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryGalleryIdRoute = GalleryGalleryIdRouteImport.update({
  id: '/gallery/$galleryId',
  path: '/gallery/$galleryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageImageIdRoute = ApiImageImageIdRouteImport.update({
  id: '/api/image/$imageId',
  path: '/api/image/$imageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGalleryGalleryIdRoute = ApiGalleryGalleryIdRouteImport.update({
  id: '/api/gallery/$galleryId',
  path: '/api/gallery/$galleryId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gallery/$galleryId': typeof GalleryGalleryIdRoute
  '/view/$imageId': typeof ViewImageIdRoute
  '/api/gallery/$galleryId': typeof ApiGalleryGalleryIdRoute
  '/api/image/$imageId': typeof ApiImageImageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gallery/$galleryId': typeof GalleryGalleryIdRoute
  '/view/$imageId': typeof ViewImageIdRoute
  '/api/gallery/$galleryId': typeof ApiGalleryGalleryIdRoute
  '/api/image/$imageId': typeof ApiImageImageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gallery/$galleryId': typeof GalleryGalleryIdRoute
  '/view/$imageId': typeof ViewImageIdRoute
  '/api/gallery/$galleryId': typeof ApiGalleryGalleryIdRoute
  '/api/image/$imageId': typeof ApiImageImageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gallery/$galleryId'
    | '/view/$imageId'
    | '/api/gallery/$galleryId'
    | '/api/image/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gallery/$galleryId'
    | '/view/$imageId'
    | '/api/gallery/$galleryId'
    | '/api/image/$imageId'
  id:
    | '__root__'
    | '/'
    | '/gallery/$galleryId'
    | '/view/$imageId'
    | '/api/gallery/$galleryId'
    | '/api/image/$imageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalleryGalleryIdRoute: typeof GalleryGalleryIdRoute
  ViewImageIdRoute: typeof ViewImageIdRoute
  ApiGalleryGalleryIdRoute: typeof ApiGalleryGalleryIdRoute
  ApiImageImageIdRoute: typeof ApiImageImageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/view/$imageId': {
      id: '/view/$imageId'
      path: '/view/$imageId'
      fullPath: '/view/$imageId'
      preLoaderRoute: typeof ViewImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery/$galleryId': {
      id: '/gallery/$galleryId'
      path: '/gallery/$galleryId'
      fullPath: '/gallery/$galleryId'
      preLoaderRoute: typeof GalleryGalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image/$imageId': {
      id: '/api/image/$imageId'
      path: '/api/image/$imageId'
      fullPath: '/api/image/$imageId'
      preLoaderRoute: typeof ApiImageImageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gallery/$galleryId': {
      id: '/api/gallery/$galleryId'
      path: '/api/gallery/$galleryId'
      fullPath: '/api/gallery/$galleryId'
      preLoaderRoute: typeof ApiGalleryGalleryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalleryGalleryIdRoute: GalleryGalleryIdRoute,
  ViewImageIdRoute: ViewImageIdRoute,
  ApiGalleryGalleryIdRoute: ApiGalleryGalleryIdRoute,
  ApiImageImageIdRoute: ApiImageImageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
